package bloomingflower;

import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class TanggalLahir extends javax.swing.JFrame {


    public TanggalLahir() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        initComponents();
    }

     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        bulan = new javax.swing.JTextField();
        tahun = new javax.swing.JTextField();
        batal = new javax.swing.JButton();
        lanjut = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel2.setText("Silahkan Masukkan Tangal Lahir Anda :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 277, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel3.setText("Tanggal");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 334, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel4.setText("Bulan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 397, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel5.setText("Tahun");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 463, -1, -1));

        tanggal.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });
        jPanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 334, 362, -1));

        bulan.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        bulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanActionPerformed(evt);
            }
        });
        jPanel1.add(bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 397, 362, -1));

        tahun.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunActionPerformed(evt);
            }
        });
        jPanel1.add(tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 460, 362, -1));

        batal.setBackground(new java.awt.Color(255, 168, 168));
        batal.setFont(new java.awt.Font("Goudy Old Style", 1, 40)); // NOI18N
        batal.setForeground(new java.awt.Color(255, 255, 255));
        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel1.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 568, -1, -1));

        lanjut.setBackground(new java.awt.Color(255, 168, 168));
        lanjut.setFont(new java.awt.Font("Goudy Old Style", 1, 40)); // NOI18N
        lanjut.setForeground(new java.awt.Color(255, 255, 255));
        lanjut.setText("Lanjut");
        lanjut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lanjutMouseClicked(evt);
            }
        });
        lanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanjutActionPerformed(evt);
            }
        });
        jPanel1.add(lanjut, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 568, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Petunjuk : Isi tanggal lahir dengan angka");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 523, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloomingflower/awal nocreat.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 0, -1, -1));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 333, 90, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloomingflower/bungakanan.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloomingflower/bungakiri.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(934, 333, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void tahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunActionPerformed

    private void bulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bulanActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed
    public void kotakPesan() {
            JOptionPane.showMessageDialog(null,"Isi Semua Data Terlebih Dahulu");
        }  
    private void lanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanjutActionPerformed
        if (tanggal.getText().equals("")){
            kotakPesan();
        }
        else if (bulan.getText().equals("")){
            kotakPesan();
        }
        else if (tahun.getText().equals("")){
            kotakPesan();
        }
    }//GEN-LAST:event_lanjutActionPerformed

    private void lanjutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lanjutMouseClicked
        MaknaBunga masuk = new MaknaBunga();
        int w = Integer.parseInt(tanggal.getText());
        //jika data tanggal diisi tidak sesuai maka akan timbul dialog box
        if (w > 32){
            JOptionPane.showMessageDialog(null,"Tolong Isi Data Dengan Benar.");
        }
        else{
            int x = Integer.parseInt(bulan.getText());
            if (x == 1) {
                String z = "Bunga Anyelir";
                String y="Anyelir disebut sebagai bunga para dewa. Anyelir juga diangap sebagai salah satu bunga budidaya tertua di dunia, penuh dengan simbolisme dan legenda. Seseorang yang memiliki bunga Anyelir sebagai bunga kelahiran sangat termotivasi untuk berhasil dan mendapatkan posisi kekuasaan dalam kehidupan.";
                masuk.maknanya(y);
                masuk.my_update(z);
                masuk.setVisible(true);
                dispose();
            }
            if (x == 2) {
                String z = "Bunga Iris";
                masuk.my_update(z);
                String y="Bunga Iris memiliki arti cinta, kesetiaan, kesejahteraan, keagungan, kemuliaan, dan harapan. Bunga Iris juga memiliki makna kebijaksanaan. Konon, bila seseorang memimpikan bunga Iris, bakal ada keberuntungan yang menghampiri.  Seseorang yang memiliki bunga Iris sebagai bunga kelahiran biasanya mempunyai intuisi yang akurat, akal sehat yang luar biasa, kecerdikan, dan kemauan yang kuat. ";
                masuk.maknanya(y);
                masuk.setVisible(true);
                this.dispose();
            }
            if (x == 3) {
                String z = "Bunga Daffodil";
                masuk.my_update(z);
                String y="Bunga Daffodil memiliki arti yaitu kelahiran kembali dengan janji kebahagiaan dan sukacita. Bunga Daffodil mewakili simbol optimisme, hormat, kebaikan dan kehangatan cinta tak berbalas. Kamu dapat dengan mudah beradaptasi dengan situasi yang berbeda dan dapat menangani tugas yang berbeda pada saat yang bersamaan. Salah satu ciri terbesarnya adalah kamu biasanya menghindari konflik dan cenderung bertindak sebagai pembawa damai ketika yang lain bertempur.";
                masuk.maknanya(y);
                masuk.setVisible(true);
                this.dispose();
            }
            if (x == 4) {
                String z = "Bunga Daisy";
                masuk.my_update(z);
                String y="Bunga Daisy mempunyai arti kepolosan, keceriaan dan kesimpatikan. Bunga ini juga kerap dipakai seorang pria untuk melamar kekasihnya. Bunga Daisy ini juga terkenal akan kemampuannya menyembuhkan penyakit penyakit tertentu. Kamu yang memiliki bunga kelahiran ini adalah orang yang kompetitif dan termotivasi, kamu juga dapat membuat hidup semua orang menjadi indah di mana pun kamu berada.";
                masuk.maknanya(y);
                masuk.setVisible(true);
                this.dispose();
            }
            if (x == 5) {
                String z = "Bunga Lily of The Valley";
                masuk.my_update(z);
                String y="Bunga Lily of the Valley adalah simbol dari manis, rendah hati, kesetiaan dan kembali pada kebahagiaan. Bunga ini juga dipercaya membawa kebahagian serta kesetiaan pasangan. Bagi kamu yang memiliki Lily of the Valley sebagai bunga kelahiran biasanya memiliki sifat keras kepala dan sensitif. Namun, dengan kemauan yang kuat, kamu dapat dengan berani menangani kesulitan hidup.";
                masuk.maknanya(y);
                masuk.setVisible(true);
                this.dispose();
            }
            if (x == 6) {
                String z = "Bunga Mawar";
                masuk.my_update(z);
                String y="Bunga mawar memiliki arti rasa cinta, romantis, kecantikan dan kesempurnaan. Namun tergantung dari warnanya, mawar juga dapat memiliki arti rasa kagum, rasa syukur, kepedulian, pertemanan, dan kesucian. Sekuntum bunga mawar yang belum mekar bisa juga melambangkan “cinta pertama”. Kamu yang memiliki Mawar sebagai bunga kelahiran biasanya mudah beradaptasi dalam situasi apa pun. kamu juga secara alami memiliki kemampuan komunikasi yang baik dan rasa keingintahuan.";
                masuk.maknanya(y);
                masuk.setVisible(true);
                this.dispose();
            }
            if (x == 7) {
                String z = "Bunga Larkspur";
                masuk.my_update(z);
                String y="Bunga Larkspur adalah bunga yang menyimbolkan keberuntungan, keringanan dan gelak tawa. Bunga ini jugamenunjukkan \"ikatan cinta yang kuat\". Selain hati yang terbuka dan keterikatan, bunga Larkspur pertanda perasaan tanpa beban. Kamu yang memiliki bunga Larkspur sebagai bunga kelahiran biasanya merupakan orang yang gemar bekerja, perfeksionis dan cukup kritis. Bunga ini juga menggambarkan keunikan alami dari seseorang.";
                masuk.maknanya(y);
                masuk.setVisible(true);
                this.dispose();
            }
            if (x == 8) {
                String z = "Bunga Gladiol";
                masuk.my_update(z);
                String y="unga Gladiol memiliki arti kenangan manis, ketulusan. Namanya yang diambil dari kata gladius atau gladiator, bunga ini juga mengandung makna integritas kekuatan dan juga obsesi. Bunga Gladiol mewakili simbol kekuatan karakter, pernikahan dan keluarga. Kamu yang memiliki bunga Gladiol sebagai bunga kelahiran biasanya sangat termotivasi oleh keinginan untuk berhasil. Kamu dengan bunga kelahiran Gladiol adalah orang yang menakjubkan dan intelektual.";
                masuk.maknanya(y);
                masuk.setVisible(true);
                this.dispose();
            }
            if (x == 9) {
                String z = "Bunga Aster";
                masuk.my_update(z);
                String y="Bunga Aster melambangkan keyakinan, pengabdian, dan keberanian. Bunga ini juga melambangkan cinta, kekaguman, kepuasan dan tidak dapat diprediksi. Kamu yang memiliki Aster sebagai bunga kelahiran diyakini memiliki pengabdian yang kuat untuk hidup. Kamu juga selalu menggabungkan logika dan intuisi dalam menghadapi kehidupan. Satu lagi, kamu diklasifikasikan sebagai seorang yang perfeksionis.";
                masuk.maknanya(y);
                masuk.setVisible(true);
                this.dispose();
            }
            if (x == 10) {
                String z = "Bunga Marigold";
                masuk.my_update(z);
                String y="Bunga Marigold adalah bunga penanda optimisme dan kemakmuran.  Kamu yang lahir dengan bunga Marigold sebagai bunga kelahiran adalah mereka yang sangat termotivasi oleh keadilan dan selalu menciptakan keselarasan di semua bidang kehidupan. Mereka memiliki kepribadian yang lembut dan suka mengambil tantangan. Mereka adalah 'pembawa damai' dan biasanya tidak suka berkelahi dengan yang lain. Menjadi komunikator yang baik, dan biasanya cenderung meyakinkan orang dan dianggap sebagai pemimpin.";
                masuk.maknanya(y);
                masuk.setVisible(true);
                this.dispose();
            }
            if (x == 11) {
                String z = "Bunga Krisan";
                masuk.my_update(z);
                String y="Bunga Krisan memiliki arti makna keceriaan, pesona, optimis, kelimpahan, keberuntungan, persahabatan dan cinta rahasia. Kamu yang memiliki Krisan sebagai bunga kelahiran biasanya merupakan sosok yang kuat, pribadi dan dominan. Mereka tertarik dan bercita-cita hanya untuk kebenaran. Kamu adalah seseorang berintelektual, pendiam, dan super magnetik. ";
                masuk.maknanya(y);
                masuk.setVisible(true);
                this.dispose();
            }
            if (x == 12) {
                String z = "Bunga Narcissus";
                masuk.my_update(z);
                String y="Bunga Narcissus seperti matahari yang memiliki arti janji setia kepada pasangan selamanya. Bunga Narcissus juga berarti pengharapan kepada orang yang dicintai tetap seperti apa adanya. Mereka yang meiliki bunga narcissus adalah orang yang sangat bekerja keras, mandiri, dan menghormati tradisi. Mereka sangat terikat dengan keluarga mereka dan dapat melakukan apa saja untuk melindungi keluarganya.";
                masuk.maknanya(y);
                masuk.setVisible(true);
                this.dispose();
            }
            //jika data bulan diisi tidak sesuai maka akan timbul dialog box
            if(x > 12) {
                JOptionPane.showMessageDialog(null,"Tolong Isi Data Dengan Benar.");
            }
        }
    }//GEN-LAST:event_lanjutMouseClicked

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        int dialogButton = JOptionPane.showConfirmDialog (null, "Anda Akan Keluar.\n"
            + "Apa Anda Yakin?","PERINGATAN",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(dialogButton == JOptionPane.YES_OPTION) {
            System.exit(0);}
    }//GEN-LAST:event_batalActionPerformed

   
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TanggalLahir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JTextField bulan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lanjut;
    private javax.swing.JTextField tahun;
    private javax.swing.JTextField tanggal;
    // End of variables declaration//GEN-END:variables

    

        
    
}
